### ISSUE TITLE
Installation instructions to README?

### ISSUE THREAD

**Issue by orschiro** [hoyon/mpv-mpris#10]
Dear @hoyon,

Thank you! I would love to try your plugin and control mpv from my media keys. 

But how do I do it?

Can we add installation instructions to your README?

I am on Linux Mint 18.3. 

Thank you!

**Comment by orschiro** [comment]
Thank you! That makes it more clear. 

Question: 

Can MPV compiled and shipped with your plugin directly integrated?

If so, I would request at Ubuntu to package MPV with your great plugin included. :-)

**Comment by hoyon** [comment]
I don't think so. There is no system wide script directory for mpv - the default lua scripts, such as youtube-dl, are compiled directly into the binary. 

You would either have to copy `mpris.so` into the user scripts directory or create a patch for mpv allowing scripts to be loaded from a system wide directory, or indeed simply patch my code into mpv.

**Comment by orschiro** [comment]
I see. Thank you!

Could you provide a compiled `mpris.so`?

**Comment by hoyon** [comment]
I've added a compiled `mpris.so` to the 0.1 release for Linux 64bit.

**Comment by orschiro** [comment]
Thank you so much!

Now I just have to get mpv version 0.26 on Linux Mint 18.3. :-D

```
orschiro@x230 ~ $ mpv --version
mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.11-0ubuntu0.16.04.1
```
