### ISSUE TITLE
mpv won't respond to PlayPause

### ISSUE THREAD

**Issue by tsjnachos117** [hoyon/mpv-mpris#12]
Hello. Thank you for this awesome library of awesomeness. Did I mention that this awesome library of awesomeness is awesome?

I have noticed an annoying bug. If you pause mpv, and rewind the current file to the beginning, mpv will ignore the `org.mpris.MediaPlayer.Player.PlayPause` command/signal/whatever.  If I send `org.mpris.MediaPlayer.Player.Play`, the player responds as expected. Also, if I *don't* rewind to the beginning, there's no problem.

I can still send the Next and Previous signal-thinggies, and they work as expected. I haven't tested any other dbus/mpris signal-thinngies.

I'm running version `git-2018-05-17-05b392b` on Ubuntu 18.04. I only compiled mpv-mpris a few days ago, so I'm assuming it's still the newest version.

Also, as you may have already guessed, I don't really know much about dbus, hence my constant use of the term "thinggies".

**Comment by hoyon** [comment]
Thanks for the bug report and feedback. Greatly appreciated! 

This should fix the issue.

**Comment by tsjnachos117** [comment]
Wow, that was fast. Thanks for the fix.
