### ISSUE TITLE
Seeking mpv using arrow keys / seek commands does not update seek position in mpris

### ISSUE THREAD

**Issue by mralext20** [hoyon/mpv-mpris#15]
repro steps:
play media
hit the left arrow button a bunch of times to move the seek position

observe seek position in a mpris compatible tool (KDE's media player, for example)

notice that the seek position and actual seek location are different

**Comment by mralext20** [comment]
after a bit more testing, it appears to be more reproducible by holding down the arrow up or down keys with default bindings.

**Comment by hoyon** [comment]
I've tested this using the KDE media player and the time when seeked is consistent with mpv until around 35:45 on a long file, where it goes back to the beginning. 

That time is 2145 seconds which, in microseconds, is suspiciously close to 2^31 − 1, the largest number which can be stored in a 32 bit signed integer, which is what the KDE media player must be using internally and causing the issue. 

For some reason, the MPRIS creators thought that we needed microsecond precision when seeking tracks, so the internal numbers are rather large and need to be handled with 64 bit integers.

The same issue is also present in VLC player.

**Comment by mralext20** [comment]
so its a kde bug?

**Comment by hoyon** [comment]
It seems so. You should create a bug report on the relevant kde bug tracker
