### ISSUE TITLE
Would it make sense to send a PlaybackStatus Stopped on quit?

### ISSUE THREAD

**Issue by timakro** [hoyon/mpv-mpris#22]
Not sure if this is against the spec but it would be useful when used with gpodder.

**Comment by hoyon** [comment]
Why would this behaviour be useful for gpodder? I'm not really familiar with it.

I'm not against such a feature, but I'm also not sure why it would be desired - surely the application quitting and the bus disappearing would imply playback has stopped?

**Comment by timakro** [comment]
gpodder is tracking the position you were last listening. Like this it can only tell when you pause the playback before quitting.

**Comment by jonath92** [comment]
I also would like to see this. I am using the plugin for the [Linux Mint Radio Applet](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/radio@driglu4it) and this would make my code much cleaner.

**Comment by hoyon** [comment]
Fixed in https://github.com/hoyon/mpv-mpris/commit/c688351d1ac7c4c9b669196ab4e1c40631a344e1
