### ISSUE TITLE
sound volume support

### ISSUE THREAD

**Issue by nerijus** [hoyon/mpv-mpris#3]
It would be nice to implement it. For example, https://github.com/dodo/lua-mpris supports it.

**Comment by hoyon** [comment]
Ah I somehow forgot to properly implement/test this. Fixed in 6a26db35cf91838f21e805213ba590dbe661a820

**Comment by nerijus** [comment]
It changes volume now, but the slider stays at maximum (using kdeconnect).

**Comment by hoyon** [comment]
Ah sorry forgot to also adjust the volume for the signal. mpv gives volumes from 0-100, wheras mpris requires 0-1. Can you try again now?

**Comment by nerijus** [comment]
It's OK now, thanks!
