### ISSUE TITLE
[FR] Thumbnail support

### ISSUE THREAD

**Issue by ReekyMarko** [hoyon/mpv-mpris#34]
Some mpris clients make use of album art, most notably KDE Connect. When I listen to music on MPD with the MPDris plugin, KDE Connect gets the album art from the mpris protocol and displays it on my phone. Example data with playerctl: 
```
$ playerctl metadata | grep artUrl
playerctld mpris:artUrl              file:///home/frodo/Music/Eminem/Relapse/cover.jpg
```

It would be very nice to do the same thing when I watch a youtube video with mpv and mpv-mpris. Local files obviously wouldn't have a thumbnail.

At least on the command line, you can get the thumbnail URL like this:
```
$ youtube-dl --list-thumbnails "https://www.youtube.com/watch?v=HaMjPs66cTs"
[info] Thumbnails for HaMjPs66cTs:
ID  width    height  URL
0   unknown  unknown https://i.ytimg.com/vi/HaMjPs66cTs/maxresdefault.jpg
```

So in the end it would just involve getting the thumbnail URL and publishing it as artUrl. What do you think, is this something that is worth it to implement in this plugin?

**Comment by UtkarshVerma** [comment]
I'd also love to have this feature!
+1

**Comment by ReekyMarko** [comment]
Awesome, just built the latest master and it works beautifully!

**Comment by UtkarshVerma** [comment]
Thanks for the quick implementation!

**Comment by barolo** [comment]
Did it stop to work? It doesn't get the cover no matter what for me

**Comment by hoyon** [comment]
@barolo Embedded images aren't supported as afaik there's no way to get it from mpv and reading the file manually doesn't seem worth the effort.

PR welcome to add missing thumbnail filenames.
