### ISSUE TITLE
Still cannot install (enabled cplugins)

### ISSUE THREAD

**Issue by bajtekv** [hoyon/mpv-mpris#39]
Hello, I would like to get any pieces of advice about how to install mpv-mpris. I'm working on script for gotubecast so I need this plugin.

I builded mpv 0.32.0-514-g502e798 succesfully on my pc with command **./scripts/mpv-build --enable-cplugins**.

I got an error while installing mpris:

_mpris.c: In function 'mpv_open_cplugin':
mpris.c:968:32: error: 'G_BUS_NAME_OWNER_FLAGS_DO_NOT_QUEUE' undeclared (first use in this function)_
                                G_BUS_NAME_OWNER_FLAGS_DO_NOT_QUEUE,
![error](https://user-images.githubusercontent.com/56979311/82741444-1ac1a980-9d52-11ea-8092-ab814c6c9e83.png)

Thank you for your replies

**Comment by hoyon** [comment]
This is probably because you're using an outdated version of glib which is no longer supported. You can either use an older version of mpv-mpris, or upgrade your system glib library.

**Comment by hoyon** [comment]
Closing this for now. Feel free to reopen if you're still having issues with an up to date glib.
