### ISSUE TITLE
mpris.so installed but kde-connect cannot find it

### ISSUE THREAD

**Issue by shag00** [hoyon/mpv-mpris#41]
I think I followed the installation correctly - download the mpris.so file and copy it to the .config/mpv/scripts directory. Kde-connect has a multimedia control screen within which is a drop down menu where you can select the the player, for me only vlc appears. If I start mpv with the scripts option from the CLI then mpv appears on the drop down list. How to make kde-connect see mpv without having to start mpv from the CLI first?

**Comment by hoyon** [comment]
Do you have an `~/.mpv` directory? I think they changed the default mpv config directory at some point for no good reason. If so can you try put the mpris.so file in `~/.mpv/scripts`?

**Comment by shag00** [comment]
Makes no difference doing this.

**Comment by olifre** [comment]
I think the main problem is:

> How to make kde-connect see mpv without having to start mpv from the CLI first?

If I understand correctly, MPRIS by design can only work if the player is running, the same should be true for VLC — do you have it running in background / minimized to tray, probably? That would explain the difference.

**Comment by shag00** [comment]
Yes, you are correct on both counts. My work around was to start a psuedo mpv session at startup as I had to do with vlc. Rather strange logic that drives someone (kde) to develop a media player controller for a mobile phone that needs to be started from the CLI.

In that case, this issue can be closed.

________________________________

**Comment by olifre** [comment]
> Rather strange logic that drives someone (kde) to develop a media player controller for a mobile phone that needs to be started from the CLI.

I think their main focus was on MPRIS support in general, probably more in the direction of "their" music player Elisa and Plasma Integration for the browser. Funnily enough, I personally rather use KDE connect when using `mpv` to watch DVB television to pause and regulate volume, which likely never was an "intended" use case, but I love it ;-).
