### ISSUE TITLE
Spaming title, url and track id

### ISSUE THREAD

**Issue by jzbor** [hoyon/mpv-mpris#45]
I face the problem that whenever 'mpris:length' receives an update via MPRIS the title, the url and the track id get send two, even if they have not changed. This causes unneeded extra traffic on the MPRIS bus and may cause applications two act upon title updates even though there is no real update, which in turn causes unnecessary load.

EDIT: If you wonder why the length variable changes during playback: I tried watching livestreams via youtube-dl + mpv...

**Comment by hoyon** [comment]
I don't think it's possible to send specific fields when the current metadata is changed. I've tested this with gnome and if you send a metadata update without the track title for example, Gnome then shows unknown track. 

I don't think the extra load is much of an issue, given how much it is dwarfed by streaming and video playback in the first place.
