### ISSUE TITLE
Unable to make mpris.c after cloning repo

### ISSUE THREAD

**Issue by m-GDEV** [hoyon/mpv-mpris#48]
Error: 
```
fatal error: gio/gio.h: No such file or directory
```

Full output:
```
cc mpris.c -o mpris.so -std=c99 -Wall -Wextra -O2 `pkg-config --cflags gio-2.0 gio-unix-2.0 glib-2.0 mpv`  `pkg-config --libs gio-2.0 gio-unix-2.0 glib-2.0`  -shared -fPIC
Package mpv was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mpv' found
mpris.c:1:10: fatal error: gio/gio.h: No such file or directory
 #include <gio/gio.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:11: recipe for target 'mpris.so' failed
make: *** [mpris.so] Error 1
```

Not sure what to do from here, any help is appreciated!

**Comment by hoyon** [comment]
You need to install the glib development headers on your system before building. 

For Debian and derivatives you need to `apt install libglib2.0-dev`

**Comment by m-GDEV** [comment]
> You need to install the glib development headers on your system before building.
> 
> For Debian and derivatives you need to `apt install libglib2.0-dev`

Thanks for your response!

I actually did some googling beoforehand and actually installed the package you mentioned. 

For some reason it still does not work. Same error.

**Comment by hoyon** [comment]
What distro are you using and what's the output if you run `pkg-config --cflags gio-2.0 gio-unix-2.0 glib-2.0 mpv`?

**Comment by m-GDEV** [comment]
Result of above command:
 ```
Package mpv was not found in the pkg-config search path.
Perhaps you should add the directory containing `mpv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mpv' found
```

This error/message was also shown while trying to make. You can actually see it in the first comment I made on this issue.

The distro I am using is Peppermint 10 which is based off of Ubuntu 18.04 LTS.
[https://peppermintos.com/](Peppermint 10 Website)

**Comment by hoyon** [comment]
Ah you need to have the mpv development files installed (`libmpv-dev`).

`gio/gio.h` being missing is a bit of a red herring.

**Comment by m-GDEV** [comment]
^This worked! 

Thanks so much for your help! I really appreciate it!
