### ISSUE TITLE
no expose length information when play videos

### ISSUE THREAD

**Issue by sl1pkn07** [hoyon/mpv-mpris#5]
when play videos, and try to see the length of the video file:

```
└───╼  qdbus org.mpris.MediaPlayer2.mpv /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata 
mpris:trackid: 
xesam:title: Arietty's Song.mp4
```

but when play audio, the length is exposed:

```
└───╼  qdbus org.mpris.MediaPlayer2.mpv /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata 
mpris:length: 348000000
mpris:trackid: 
xesam:album: A Type   (WEB)
xesam:artist: Arkitech
xesam:genre: Hardcore
xesam:title: A Type
```

please add support for expose length when play video files

greetings

**Comment by hoyon** [comment]
Thanks for spotting this. The duration isn't usually known yet for videos when the metadata is created, meaning it isn't included. Fixed in 6e70d9e5d7484b17416da74235c528474be7da35 to update metadata when duration is known.
