### ISSUE TITLE
Feature Request: show Youtube "artist" with Playerctl

### ISSUE THREAD

**Issue by kaykay38** [hoyon/mpv-mpris#50]
There is no artist info for youtube videos when calling `playerctl metadata`. I can see artist info when I am using playerctl with Chromium-based browsers on youtube, but not in mpv.

**Comment by hoyon** [comment]
It seems mpv only recently added more metadata to the youtube-dl lua script so this might be possible when a new version of mpv is released.

See https://github.com/mpv-player/mpv/commit/cbb8f534b064f144820435148e516978de08cb30

**Comment by kaykay38** [comment]
Thank you for your quick response! I look forward to the new mpv update.
