### ISSUE TITLE
mpv-mpris shows unexpected behaviour while mpris indicator button (Gnome Shell extension) is installed

### ISSUE THREAD

**Issue by Mershl** [hoyon/mpv-mpris#55]
Original issue: https://github.com/flathub/io.mpv.Mpv/issues/23#issuecomment-950405461

A lot of config parameters of mpv are reset to default while mpv-mpris and the mpris indicator button extension is enabled. See original issue for details.

**Comment by hoyon** [comment]
It looks like the flathub package is still using version 0.5 of mpv-mpris. Can you try upgrading it to 0.6 and seeing if the problem persists? A few issues with looping were fixed in that version.
