### ISSUE TITLE
Can I use without MPV

### ISSUE THREAD

**Issue by bamper45** [hoyon/mpv-mpris#59]
I have debian 11, installed Radio ++ applet, it asks to install mpv. So is it possible without mpv, because I don't want to play for the sake of radio

**Comment by pabs3** [comment]
@bamper45 I think this issue has been filed against the wrong project. This project is mpv-mpris, but presumably you should file it against the Radio++ applet in your desktop. Please close this bug and file a new one on the Radio++ applet.
