### ISSUE TITLE
please make a release

### ISSUE THREAD

**Issue by majewsky** [hoyon/mpv-mpris#6]
Since mpv now has `--enable-cplugins` by default, I decided to give this a try and it works perfectly with all MPRIS consumers around here that I tested. Thanks very much for this fine piece of software!

Can you please cut a release (don't care whether it's 0.1 or 1.0 or whatever) so that I can package this up for Arch Linux?

**Comment by hoyon** [comment]
Thanks for the feedback. Really appreciate it!

I also use arch linux but have never written a PKGBUILD before and I was under the impression that most git packages in the AUR simply pull from master. Am I wrong? Anyway I've tagged and created a 0.1 release. Is that sufficient?

**Comment by majewsky** [comment]
Awesome, thanks for the quick response. I uploaded https://aur.archlinux.org/packages/mpv-mpris/

As for `-git` packages, I don't like them. They're always moving targets, and I feel like they could break at any given moment if the maintainer is not disciplined about what he pushes to `master`. This is less of a concern for big projects where there are a lot of checks and reviews before stuff goes to `master`, but more problematic with one-person projects. For example, I would certainly discourage anyone from installing my own projects by cloning master. :)

Secondly, my [custom repo compilation script](https://github.com/majewsky/system-configuration/blob/master/build_package.pl) gets confused by `-git` packages (it reads the `.SRCINFO` for the package version, then expects makepkg to build precisely this version), and I'm in no mood to fix that. :)
