### ISSUE TITLE
Setting or defining seek distance

### ISSUE THREAD

**Issue by niveK77pur** [hoyon/mpv-mpris#65]
I am using this plugin so that I can control MPV through the KDE Connect application. However, default seek distance is 10 seconds and I usually like to lower it to 5 seconds.

After some trial and error over the past few weeks I managed to make the seek button in KDE Connect seek by 5 seconds instead of 10 by modifying [this line](https://github.com/hoyon/mpv-mpris/blob/72945f9d60772746c68ec3191bd1faea437a6fe1/mpris.c#L547): (I tried to half the 10 seconds seek time)
```diff
--- mpris.c     2022-02-02 02:34:48.414593201 +0100
+++ m.c 2022-02-02 02:37:00.937265047 +0100
@@ -544,7 +544,7 @@
         int64_t offset_us; // in microseconds
         char *offset_str;
         g_variant_get(parameters, "(x)", &offset_us);
-        double offset_s = offset_us / 1000000.0;
+        double offset_s = 0.5 * offset_us / 1000000.0;
         offset_str = g_strdup_printf("%f", offset_s);
 
         const char *cmd[] = {"seek", offset_str, NULL};
```
This works great, but today I noticed that seeking with the slider inside of KDE Connect wrongly sets the new position. In fact, if I add a `0.5` multiplier like above, seeking with the slider by an amount `x` away from the current position, will only make it seek by `0.5 * x`. In other words, if I am currently at 10'00" in the video, and slide to 0'00", then the new position will be 5'00". Similarly going from 2'00" to 3'00" will put me at 2'30".

I therefore reckon that this `offset_s` is also used for seeking via the slider, which explains why seeking distance is off by the factor that I specified (here `0.5`, but adding a factor of `2` makes it go too far). I tried adding a factor of `0.5` or `2` to other mentions of `1000000` in the code in an attempt to counter the factor of `0.5` that I added for the offset but it ended up doing more harm than good. 

I am slowly getting the impression that seek distance should actually be specified in KDE Connect instead of mpv-mpris (especially thanks to [issue 36](https://github.com/hoyon/mpv-mpris/issues/36)) but I am creating this issue in case it can actually be done properly through mpv-mpris. ~~Also, I wouldn't know where to go to make this modification to KDE Connect~~ I was imagining a sort of `input.conf` like you have for MPV, where you can specify the distance but this further makes me believe the modification should rather happen inside of KDE Connect.

Apologies for this simple inquiry end up in such a long post. I wanted to properly highlight the issue with the slider in KDE Connect. Sliding inside of MPV properly sets the slider in KDE Connect. It does not work the other way around though after adding a factor to the offset of mpv-mpris (like mentioned above).

**Comment by hoyon** [comment]
The seek amount needs to be configured in KDE connect as mpv-mpris takes any duration in microseconds which it then converts to seconds and seeds a seek command to mpv for that amount.

I'm guessing the desync of the KDE connect slider is because it is sending the command to seek by 10s so assumes that mpv-mpris dutifully did exactly that and didn't bother going back and asking mpv-mpris what the position is.

This can only be fixed by getting KDE connect to change their default or adding an option for this.

**Comment by niveK77pur** [comment]
That makes sense, thank you very much for the clarifications!

I may or may not look into how to make this happen in KDE connect in the near future then. I think I will report back here if I ever find a solid solution or workaround, just for the sake of completeness. Unless you think it goes too much off topic, then I won't.
