### ISSUE TITLE
Cover Image in notification

### ISSUE THREAD

**Issue by clari7744** [hoyon/mpv-mpris#91]
Hello, I'm not entirely sure how to format this request, and I'd PR it myself if I could figure out C 😅
But would it be possible to use the cover metadata as the notification icon?
![Example of Notification](https://github.com/hoyon/mpv-mpris/assets/73483912/9cf50539-96a9-43f1-af26-26805da7b3e0)
Just a small thing, but would make it look nice :)

**Comment by hoyon** [comment]
Heya, mpv-mpris does use album art data if it's provided as an external file with [one of these names](https://github.com/hoyon/mpv-mpris/blob/master/mpris.c#L217), but not with embedded album art. 

Afaik mpv doesn't expose any way of getting the album art from their API so the only way it would work is for us to extract the image data ourselves. This isn't something I'm likely to work on but PRs welcome if anyone is keen!

**Comment by randomcoder67** [comment]
Does this support cover art in audio files? Using mpv-mpris with gnome's media plugin and the thumbnail works for video files, but not for audio files (m4a)

**Comment by physkets** [comment]
I'm on Gnome, and I don't see the cover art (embedded, I think):

<img width="423" height="110" alt="Image" src="https://github.com/user-attachments/assets/7174c1fd-9bcf-444f-91c5-752acc674c15" />
