### ISSUE TITLE
How to control only when focused ?

### ISSUE THREAD

**Issue by asklow** [hoyon/mpv-mpris#93]
When there's mpv & a browser playback instance present at the same time, media buttons control browser playback even though window focused on mpv. Browser superseeds mpv :C  
How to solve this issue ?  
I've tried __[`input-media-keys=<yes>|<no>`](https://mpv.io/manual/stable/#options-input-media-keys)__ but it didn't work. I'm on i3 btw.  
https://github.com/altdesktop/playerctl/issues/318

**Comment by hoyon** [comment]
This plugin exists outside of the `input-media-keys` setting in mpv and in fact doesn't provide keyboard shortcuts or anything to do with window focus.

This plugin exposes an interface via dbus which desktop environments like Gnome or KDE can then connect keyboard shortcuts and widgets to.

As you're using i3, you'll likely want to wire in a tool like playerctl into i3 which lets you specify which player you want to control. Determining which player is 'active' is up to you which is the nature of a more DIY window manager like i3.
