### ISSUE TITLE
How to make this work on Windows?

### ISSUE THREAD

**Issue by AthoyeMahmud** [hoyon/mpv-mpris#95]

**Comment by hoyon** [comment]
`mpv-mpris` is designed for systems using DBUS which doesn't include Windows.

For windows mpv has built in support for media keys with this flag so no need for any plugin https://mpv.io/manual/stable/#options-input-media-keys

**Comment by veganomy** [comment]
@hoyon  It's enabled in my mpv config but still does not work. Anything else to do ?
