### ISSUE TITLE
Can't detect installed libavformat

### ISSUE THREAD

**Issue by SDD701** [hoyon/mpv-mpris#97]
When I launch mpv I get:
```
[mpris] C plugin error: 'libavformat.so.58: cannot open shared object file: No such file or directory'
[mpris] Could not load SO plugin /home/SDD/.config/mpv/scripts/mpris.so
```
But looks like it's installed: 
```
 doas find / -name "libavformat.so"
find: '/run/user/1000/doc': Permission denied
/usr/lib/libavformat.so
/usr/lib64/libavformat.so
```
ffmpeg is installed, OS Gentoo

**Comment by kzwkt** [comment]
gentoo has libavformat.so.60 now

**Comment by olifre** [comment]
@SDD701 In case you compiled / installed manually, you need to recompile in case there was an ABI bump on any of the dependencies on your systems (e.g. on Gentoo, `media-video/ffmpeg`). 

In case you are using Gentoo, though, you may want to install `mpv-plugin/mpv-mpris` from Gentoo's [GURU](https://github.com/gentoo/guru) overlay, which takes care of updating and rebuilding when needed via your regular system updates.

**Comment by SDD701** [comment]
> @SDD701 In case you compiled / installed manually, you need to recompile in case there was an ABI bump on any of the dependencies on your systems (e.g. on Gentoo, `media-video/ffmpeg`). 
> 
> In case you are using Gentoo, though, you may want to install `mpv-plugin/mpv-mpris` from Gentoo's [GURU](https://github.com/gentoo/guru) overlay, which takes care of updating and rebuilding when needed via your regular system updates. 

I didn't know there is an ebuild in GURU. It works if installed this way,  thank you
